### ISSUE TITLE
invitar amios inexistentes

### ISSUE THREAD

**Issue by arejula27** [UNIZAR-30226-2021-02/Frontend-mobile#29]
No da error por pantalla, cuando recibe status 204

**Comment by dolansete** [comment]
Supongo que habrá que mirar el código y ver que no sea 204, ya que no da error.

**Comment by dolansete** [comment]
Añadido el caso en el frontend, se probará cuando lo suba el back-end

**Comment by dolansete** [comment]
Hecho
