### ISSUE TITLE
En el canvas cambiar colores

### ISSUE THREAD

**Issue by Merni27** [UNIZAR-30226-2021-02/Frontend-mobile#35]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dolansete** [comment]
Que no quiero

**Comment by Merni27** [comment]
Ostia no se ha guardado el texto que puse D:
Basicamente es que la linea esa o barra para seleccionar el grosor del lapiz es negro sobre gris y eso, que no se veia un pijo.

**Comment by dolansete** [comment]
Siii ya me acordaba, ya está hecho
